CREATE PROC SP_WORKER_INOUT
@WORKERBARCODE AS VARCHAR(50),
@DATE AS DATETIME,
@IOTYPE AS VARCHAR(1),
@GATEID AS INT
AS
BEGIN 
DECLARE @WORKERNAME AS VARCHAR(100)
DECLARE @WORKERID AS INT
SELECT @WORKERNAME = WORKERNAME ,@WORKERID= ID FROM WORKERS WHERE WORKERBARCODE = @WORKERBARCODE
	IF @WORKERID IS NULL

	BEGIN
		RAISERROR('OKUTULAN KART GECERSÝZDÝR',16,1)
		RETURN
	END

END
