CREATE PROC SP_WORKER_INOUT
@WORKERBARCODE AS VARCHAR(50),
@DATE AS DATETIME,
@IOTYPE AS VARCHAR(1),
@GATEID AS INT
AS
BEGIN 
DECLARE @WORKERNAME AS VARCHAR(100)
DECLARE @WORKERID AS INT
SELECT @WORKERNAME = WORKERNAME ,@WORKERID= ID FROM WORKERS WHERE WORKERBARCODE = @WORKERBARCODE
	IF @WORKERID IS NULL

	BEGIN
		RAISERROR('OKUTULAN KART GECERSÝZDÝR',16,1)
		RETURN
	END
DECLARE @LASTIO AS VARCHAR(1)

SELECT TOP(1) @LASTIO=IOTYPE FROM WORKERTRANSACTIONS WHERE WORKERID = 1 AND DATE_ >= CONVERT(DATE,GETDATE()) 
ORDER BY DATE_ DESC

	IF @LASTIO = @IOTYPE
	BEGIN
			IF @IOTYPE ='G'
				BEGIN
					RAISERROR('ZATEN ÝÇERÝDE GÖRÜNÜYORSUNUZ,GÝRÝÞ YAPAMAZSINIZ',16,1)
					RETURN
				END
			IF @IOTYPE ='C'
				BEGIN
					RAISERROR('ZATEN DIÞARIDA GÖRÜNÜYORSUNUZ,ÇIKIÞ YAPAMAZSINIZ',16,1)
					RETURN
				END
	 END

	 INSERT INTO WORKERTRANSACTIONS(WORKERID,DATE_,IOTYPE,GATEID) VALUES(@WORKERID,@DATE,@IOTYPE,@GATEID)
END