SELECT 
C.CITY SEHIR,D.DATE_ TARIH,
ISNULL((
	SELECT SUM(TOTALPRICE) FROM ORDERS O
	JOIN ADDRESS A ON A.ID = O.ADDRESSID
	WHERE A.CITYID = C.ID AND CONVERT(DATE,O.DATE_) = D.DATE_
),0) TOPLAMCIRO
FROM CITIES C
CROSS APPLY (SELECT * FROM DATES) D
WHERE C.CITY ='ARTVÝN'

 
 
