SELECT 
DATEPART(YEAR,O.DATE_) YIL ,DATEPART(MONTH,O.DATE_) AY,
CASE 
	WHEN DATEPART(MONTH,O.DATE_)=1 THEN 'OCAK'
	WHEN DATEPART(MONTH,O.DATE_)=2 THEN 'SUBAT'
	WHEN DATEPART(MONTH,O.DATE_)=3 THEN 'MART'
	WHEN DATEPART(MONTH,O.DATE_)=4 THEN 'NÝSAN'
	WHEN DATEPART(MONTH,O.DATE_)=5 THEN 'MAYIS'
	WHEN DATEPART(MONTH,O.DATE_)=6 THEN 'HAZÝRAN'
	WHEN DATEPART(MONTH,O.DATE_)=7 THEN 'TEMMUZ'
	WHEN DATEPART(MONTH,O.DATE_)=8 THEN 'AGUSTOS'
	WHEN DATEPART(MONTH,O.DATE_)=9 THEN 'EYLÜL'
	WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'EKÝM'
	WHEN DATEPART(MONTH,O.DATE_)=11 THEN 'KASIM'
	WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'ARALIK'

END  AS AY,
SUM(AMOUNT) TOPLAMMIKTAR,
SUM(LINETOTAL) TOPLAMTUTAR,
COUNT(OD.ID) URUNSAYISI,
COUNT(DISTINCT O.ID) AS MUSTERISAYISI

FROM     dbo.ORDERDETAILS AS OD INNER JOIN
                  dbo.ORDERS AS O ON OD.ORDERID = O.ID INNER JOIN
                  dbo.ITEMS AS ITM ON ITM.ID = OD.ITEMID INNER JOIN
                  dbo.USERS AS U ON U.ID = O.USERID INNER JOIN
                  dbo.ADDRESS AS A ON A.ID = O.ADDRESSID INNER JOIN
                  dbo.COUNTRIES AS C ON C.ID = A.COUNTRYID INNER JOIN
                  dbo.CITIES AS CT ON CT.ID = A.CITYID INNER JOIN
                  dbo.TOWNS AS T ON T.ID = A.TOWNID INNER JOIN
                  dbo.PAYMENTS AS P ON P.ORDERID = O.ID

GROUP BY DATEPART(YEAR,O.DATE_)  ,DATEPART(MONTH,O.DATE_)
ORDER BY DATEPART(YEAR,O.DATE_) 