SELECT 
O.ID,O.DATE_,OD.*,OD.AMOUNT,OD.UNITPRICE,OD.LINETOTAL
FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
WHERE DATE_ BETWEEN '20220101' AND '2022-01-31 23:59:59'
 
ORDER BY DATE_ DESC

SELECT * FROM ORDERS
SELECT * FROM ORDERDETAILS