SELECT 
O.ID,O.DATE_,
I.ITEMCODE,I.ITEMNAME,I.BRAND,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,
OD.*,OD.AMOUNT,OD.UNITPRICE,OD.LINETOTAL
FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE DATE_ BETWEEN '20220101' AND '2022-01-31 23:59:59'
ORDER BY DATE_ DESC