SELECT 
O.ID SIPARISNO,O.DATE_ SIPARISTARIHI, 
I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI,I.BRAND MARKA,I.CATEGORY1 KATEGORI1,I.CATEGORY2 KATEGORI2,I.CATEGORY3 KATEGORI3,
OD.UNITPRICE BIRIMFIYATI,OD.AMOUNT MIKTAR,OD.LINETOTAL SATIRTOPLAM
FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE DATE_ BETWEEN '20220101' AND '2022-01-31 23:59:59'
ORDER BY DATE_ DESC