--ÜRÜN ANALÝZÝ

-- JOIN
SELECT 
I.ID,I.ITEMCODE,I.ITEMNAME,I.BRAND,SUM(OD.AMOUNT) TOPLAMADET,
SUM(OD.LINETOTAL) TOPLAM_CIRO,
MIN(OD.UNITPRICE) ENDUSUK_FIYAT,
MAX(OD.UNITPRICE) ENYUKSEK_FIYAT,
ROUND(AVG(OD.UNITPRICE),2) ORTALAMA_FIYAT
FROM ITEMS I
JOIN ORDERDETAILS OD ON OD.ITEMID = I.ID
GROUP BY I.ID,I.ITEMCODE,I.ITEMNAME,I.BRAND

--SUBQUERY
SELECT 
I.ID,I.ITEMCODE,I.ITEMNAME,I.BRAND,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=I.ID)TOPLAMADET,
(SELECT SUM(LINETOTAL) FROM ORDERDETAILS WHERE ITEMID=I.ID)TOPLAM_CIRO,
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=I.ID)ENDUSUK_FIYAT,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=I.ID)ENYUKSEK_FIYAT,
(SELECT ROUND(AVG(UNITPRICE),2) FROM ORDERDETAILS WHERE ITEMID=I.ID)ORTALAMA_FIYAT
FROM ITEMS I
 