SELECT DISTINCT INVOICENO FATURANO,DATE_ ISLEM_BASLAMA_ZAMANI,
INVOICEDATE ISLEM_BITIS_ZAMANI,
DATEDIFF(SECOND,DATE_,INVOICEDATE) BEKLEME_ZAMANI
FROM LAB04

SELECT   INVOICENO FATURANO,
	MIN(DATE_) ISLEM_BASLAMA_ZAMANI,
	MIN(INVOICEDATE) ISLEM_BITIS_ZAMANI,
	DATEDIFF(SECOND,MIN(DATE_),MIN(INVOICEDATE)) BEKLEME_ZAMANI
FROM LAB04
GROUP BY INVOICENO
ORDER BY 1 
 