SELECT ID,NAME_,SURNAME
,NAME_+' '+SURNAME
,CONCAT(NAME_,' ',SURNAME)
FROM LAB01 
UPDATE LAB01 SET NAMESURNAME=NAME_+' '+SURNAME
UPDATE LAB01 SET NAMESURNAME=''
UPDATE LAB01 SET NAMESURNAME=CONCAT(NAME_,' ',SURNAME)

