SELECT 
CITY SEHIR,AVG(WAITTIME) ORTALAMA_KASADA_BEKLEMEZAMANI
FROM 
(
	SELECT DISTINCT INVOICENO,CITY,
	DATE_,INVOICEDATE, DATEDIFF(SECOND,DATE_,INVOICEDATE) WAITTIME
	FROM LAB05
) T
GROUP BY CITY 
ORDER BY 2