
DECLARE @ITEMID AS INT
DECLARE @DATE AS DATETIME
DECLARE @AMOUNT AS INT
DECLARE @IOTYPE AS INT

SELECT * FROM ITEMS
SELECT ROUND(RAND()*4,0)

INSERT INTO ITEMTRANSACTIONS
(ITEMID,DATE_,AMOUNT,IOTYPE)
VALUES()