
/*'Say?n Rabia Avc?,
55. Ya??n?z? kutlar, bu do?um gününüzde sizlere 1.000
TL hediye çeki vermekten mutluluk duyar?z.
Güzel günlerde harcaman?z dile?iyle...'*/

DECLARE @MONTH AS INT
DECLARE @DAY AS INT
SET @MONTH=DATEPART(MONTH,GETDATE())
SET @DAY=DATEPART(DAY,GETDATE())
DECLARE @NAME AS VARCHAR(100)
DECLARE @SURNAME AS VARCHAR(100)
DECLARE @NAMESURNAME AS VARCHAR(100)
DECLARE @AGE AS INT
DECLARE @BIRTHDATE AS DATE
DECLARE @MSG AS VARCHAR(1000)

SELECT  TOP 1 
@NAME=NAME_,@SURNAME=SURNAME,@BIRTHDATE=BIRTHDATE  FROM LAB03
WHERE DATEPART(MONTH,BIRTHDATE)=@MONTH 
AND DATEPART(DAY,BIRTHDATE)=@DAY 

ORDER BY NEWID()

SET @NAMESURNAME=@NAME+' '+@SURNAME
SET @AGE=DATEDIFF(YEAR,@BIRTHDATE,GETDATE())

SET @MSG='Say?n <NAMESURNAME>,
<AGE>. Ya??n?z? kutlar, bu do?um gününüzde sizlere 1.000
TL hediye çeki vermekten mutluluk duyar?z.
Güzel günlerde harcaman?z dile?iyle...'

SET @MSG=REPLACE(@MSG,'<NAMESURNAME>',@NAMESURNAME)
SET @MSG=REPLACE(@MSG,'<AGE>',CONVERT(VARCHAR,@AGE))

SELECT @NAMESURNAME,@AGE,@MSG 
PRINT @MSG 

 