DECLARE @NAME AS VARCHAR(100)
DECLARE @SURNAME AS VARCHAR(100)
DECLARE @NAMESURNAME AS VARCHAR(100)

SET @NAME='ÖMER'
SET @SURNAME='ÇOLAKO?LU'

SET @NAMESURNAME=@NAME+' '+@SURNAME
--SET @NAMESURNAME=CONCAT(@NAME,' ',@SURNAME)

SELECT @NAMESURNAME
PRINT @NAMESURNAME

