/*SELECT * FROM NAMES 
SELECT * FROM SURNAMES
SELECT * FROM CITIES
*/
DECLARE @NAME AS VARCHAR(100)
DECLARE @GENDER AS VARCHAR(1)
DECLARE @SURNAME AS VARCHAR(100)
DECLARE @CITY AS VARCHAR(100)
DECLARE @BIRTHDATE AS DATE
DECLARE @NAMESURNAME AS VARCHAR(100)
DECLARE @RAND AS INT

SET @RAND=1+RAND()*609
SELECT TOP 1 @NAME=NAME_,@GENDER=GENDER FROM NAMES WHERE ID=@RAND 

SET @RAND=1+RAND()*797
SELECT TOP 1 @SURNAME=SURNAME FROM SURNAMES WHERE ID=@RAND 

SET @RAND=RAND()*50*365
SET @BIRTHDATE=DATEADD(DAY,@RAND,'1950-01-01')

SET @NAMESURNAME=@NAME+' '+@SURNAME
SELECT @NAME NAME_,@GENDER GENDER,@SURNAME SURNAME,@NAMESURNAME NAMESURNAME,@BIRTHDATE BIRTHDATE