DECLARE @BEGDATE AS DATE='2022-04-01'
DECLARE @ENDDATE AS DATE='2022-05-01'
DECLARE @CITY AS VARCHAR(100)='ANKARA,?ZM?R,?STANBUL,ADANA,KONYA'


SELECT CITY,SUM(TOTALPRICE) FROM LAB07
WHERE DATE_ BETWEEN @BEGDATE AND @ENDDATE
AND CITY IN (SELECT value FROM string_split(@CITY,',') ) 
GROUP BY CITY 
