SELECT 
CASE 
	WHEN MONTH(DATE_)=1 THEN '01.Ock'
	WHEN MONTH(DATE_)=2 THEN '02.?ub'
	WHEN MONTH(DATE_)=3 THEN '03.Mar'
	WHEN MONTH(DATE_)=4 THEN '04.Nis'
	WHEN MONTH(DATE_)=5 THEN '05.May'
	WHEN MONTH(DATE_)=6 THEN '06.Haz'
	WHEN MONTH(DATE_)=7 THEN '07.Tem'
	WHEN MONTH(DATE_)=8 THEN '08.Agu'
	WHEN MONTH(DATE_)=9 THEN '09.Eyl'
	WHEN MONTH(DATE_)=10 THEN '10.Ekm'
	WHEN MONTH(DATE_)=11 THEN '11.Kas'
	WHEN MONTH(DATE_)=12 THEN '12.Ara'
END AS MONTHNAME_,
ROUND(SUM(TOTALPRICE),0) TOTALPRICE
FROM SALES
GROUP BY MONTH(DATE_)
ORDER BY 1 