DECLARE @TOTALPRICE AS FLOAT
DECLARE @AVGPRICE AS FLOAT
SELECT @TOTALPRICE=SUM(TOTALPRICE) FROM SALES 
SET @AVGPRICE=@TOTALPRICE/81

--SELECT @TOTALPRICE,@AVGPRICE

SELECT CITY,ROUND(SUM(TOTALPRICE),0) TOTALPRICE,
IIF(SUM(TOTALPRICE)>@AVGPRICE,'Ortalaman?n Üstünde','Ortalaman?n Alt?nda') STATUS
FROM SALES 
GROUP BY CITY 
ORDER BY CITY 

SELECT CITY,ROUND(SUM(TOTALPRICE),0) TOTALPRICE,
CASE 
	WHEN SUM(TOTALPRICE)>=@AVGPRICE THEN 'Ortalaman?n Üstünde'
	ELSE 'Ortalaman?n Alt?nda'
END AS STATUS

FROM SALES 
GROUP BY CITY 
ORDER BY CITY 