CREATE VIEW VW_GORE_SATISLAR AS
SELECT 
DATEPART(YEAR,O.DATE_) YIL ,DATEPART(MONTH,O.DATE_) AY,
SUM(AMOUNT) TOPLAMMIKTAR,
SUM(LINETOTAL) TOPLAMTUTAR,
COUNT(OD.ID) URUNSAYISI,
COUNT(DISTINCT O.ID) AS MUSTERISAYISI

FROM     dbo.ORDERDETAILS AS OD INNER JOIN
                  dbo.ORDERS AS O ON OD.ORDERID = O.ID INNER JOIN
                  dbo.ITEMS AS ITM ON ITM.ID = OD.ITEMID INNER JOIN
                  dbo.USERS AS U ON U.ID = O.USERID INNER JOIN
                  dbo.ADDRESS AS A ON A.ID = O.ADDRESSID INNER JOIN
                  dbo.COUNTRIES AS C ON C.ID = A.COUNTRYID INNER JOIN
                  dbo.CITIES AS CT ON CT.ID = A.CITYID INNER JOIN
                  dbo.TOWNS AS T ON T.ID = A.TOWNID INNER JOIN
                  dbo.PAYMENTS AS P ON P.ORDERID = O.ID

GROUP BY DATEPART(YEAR,O.DATE_)  ,DATEPART(MONTH,O.DATE_)
