CREATE VIEW VW_SIPARIS_DETAYLI
AS
SELECT TOP(1000)
U.USERNAME_, U.NAMESURNAME,u.TELNR1,U.TELNR2,

C.COUNTRY, CT.CITY, T.TOWN, A.ADDRESSTEXT, 
O.ID, O.DATE_, ITM.ITEMCODE, ITM.ITEMNAME, ITM.BRAND, 
ITM.CATEGORY1 KATEGORI1,ITM.CATEGORY2 KATEGORI2,ITM.CATEGORY3 KATEGORI3,ITM.CATEGORY4 KATEGORI4,
OD.AMOUNT, OD.UNITPRICE, OD.LINETOTAL SATIRTOPLAM,
CONVERT(DATE,O.DATE_) AS SIPARISTARIH,CONVERT(TIME,O.DATE_) AS SIPARISZAMANI,
DATEPART(YEAR,O.DATE_) AS YIL,
CASE 
	WHEN DATEPART(MONTH,O.DATE_)=1 THEN 'OCAK'
	WHEN DATEPART(MONTH,O.DATE_)=2 THEN 'SUBAT'
	WHEN DATEPART(MONTH,O.DATE_)=3 THEN 'MART'
	WHEN DATEPART(MONTH,O.DATE_)=4 THEN 'NÝSAN'
	WHEN DATEPART(MONTH,O.DATE_)=5 THEN 'MAYIS'
	WHEN DATEPART(MONTH,O.DATE_)=6 THEN 'HAZÝRAN'
	WHEN DATEPART(MONTH,O.DATE_)=7 THEN 'TEMMUZ'
	WHEN DATEPART(MONTH,O.DATE_)=8 THEN 'AGUSTOS'
	WHEN DATEPART(MONTH,O.DATE_)=9 THEN 'EYLÜL'
	WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'EKÝM'
	WHEN DATEPART(MONTH,O.DATE_)=11 THEN 'KASIM'
	WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'ARALIK'
END  AS AY,
CASE 
	WHEN DATEPART(DW,O.DATE_)=2 THEN '1.PZT'
	WHEN DATEPART(DW,O.DATE_)=3 THEN '2.SAL'
	WHEN DATEPART(DW,O.DATE_)=4 THEN '3.ÇRÞ'
	WHEN DATEPART(DW,O.DATE_)=5 THEN '4.PER'
	WHEN DATEPART(DW,O.DATE_)=6 THEN '5.CUM'
	WHEN DATEPART(DW,O.DATE_)=7 THEN '6.CMT'
	WHEN DATEPART(DW,O.DATE_)=1 THEN '7.PZR'

END  AS HAFTANINGUNU
FROM ORDERDETAILS AS OD INNER JOIN
                  dbo.ORDERS AS O ON OD.ORDERID = O.ID INNER JOIN
                  dbo.ITEMS AS ITM ON ITM.ID = OD.ITEMID INNER JOIN
                  dbo.USERS AS U ON U.ID = O.USERID INNER JOIN
                  dbo.ADDRESS AS A ON A.ID = O.ADDRESSID INNER JOIN
                  dbo.COUNTRIES AS C ON C.ID = A.COUNTRYID INNER JOIN
                  dbo.CITIES AS CT ON CT.ID = A.CITYID INNER JOIN
                  dbo.TOWNS AS T ON T.ID = A.TOWNID INNER JOIN
                  dbo.PAYMENTS AS P ON P.ORDERID = O.ID