
DECLARE @I AS INT=0
WHILE @I<10000
BEGIN
	DECLARE @DEVICEID AS INT
	DECLARE @LASTVALUE AS FLOAT
	DECLARE @LASTDATE AS DATETIME
	DECLARE @CURRENTVALUE AS FLOAT
	DECLARE @DATE AS DATETIME
	DECLARE @RAND AS FLOAT
	DECLARE @RAND2 AS INT

	SET @DEVICEID=1+RAND()*99

	SELECT @LASTVALUE=LASTVALUE,@LASTDATE=LASTDATE FROM THERMOMETERS
	WHERE ID=@DEVICEID

	SET @RAND=2*(-0.5+RAND())
	SET @CURRENTVALUE=ROUND(@LASTVALUE+@RAND ,2)

	SET @RAND2=15+RAND()*45
	SET @DATE=DATEADD(SECOND,@RAND2,@LASTDATE)

	--SELECT @DEVICEID DEVICEID,@LASTVALUE LASTVALUE,@LASTDATE LASTDATE,@CURRENTVALUE CURRENTVALUE,@DATE DATE_
	INSERT INTO THERMOVALUES(DEVICEID,VALUE_,DATE_)
	VALUES (@DEVICEID,@CURRENTVALUE,@DATE)
	UPDATE THERMOMETERS SET LASTDATE=@DATE,LASTVALUE =@CURRENTVALUE WHERE ID=@DEVICEID
SET @I=@I+1
END



 


 