CREATE VIEW VWBESTSELLER40
AS
SELECT TOP 40
I.ITEMCODE,I.ITEMNAME,I.BRAND,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,
SUM(OD.AMOUNT) TOPLAMMIKTAR,SUM(OD.LINETOTAL) TOPLAMSATIS
 FROM ITEMS I
JOIN ORDERDETAILS OD ON OD.ITEMID = I.ID
GROUP BY I.ITEMCODE,I.ITEMNAME,I.BRAND,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3
ORDER BY SUM(OD.LINETOTAL) DESC