CREATE VIEW VWITEMINFO
AS
SELECT 
I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI,
I.BRAND MARKA,I.UNITPRICE BIRIMFIYAT,I.CATEGORY1 KATEGORI1,
I.CATEGORY2 KATEGORI2,I.CATEGORY3 KATEGORI3,
ROUND(SUM(OD.LINETOTAL),0) TOPLAMCIRO,SUM(OD.AMOUNT) TOPLAMADET,
ROUND(SUM(OD.LINETOTAL)/SUM(OD.AMOUNT),2) ORTALAMAFIYAT,
ROUND(100*((SUM(OD.LINETOTAL)/SUM(OD.AMOUNT))-I.UNITPRICE)/I.UNITPRICE,2) KAR_YUZDE,
SUM(OD.LINETOTAL)/
(SELECT SUM(LINETOTAL) FROM ORDERDETAILS
WHERE ITEMID IN (SELECT ID FROM ITEMS WHERE CATEGORY1=I.CATEGORY1)) KATEGORI1_ORAN,

SUM(OD.LINETOTAL)/
(SELECT SUM(LINETOTAL) FROM ORDERDETAILS
WHERE ITEMID IN (SELECT ID FROM ITEMS WHERE CATEGORY2=I.CATEGORY2)) KATEGORI2_ORAN,

SUM(OD.LINETOTAL)/
(SELECT SUM(LINETOTAL) FROM ORDERDETAILS
WHERE ITEMID IN (SELECT ID FROM ITEMS WHERE CATEGORY3=I.CATEGORY3)) KATEGORI3_ORAN,

SUM(OD.LINETOTAL)/
(SELECT SUM(LINETOTAL) FROM ORDERDETAILS
WHERE ITEMID IN (SELECT ID FROM ITEMS WHERE BRAND=I.BRAND)) MARKA_ORAN
 

FROM ITEMS I 
JOIN ORDERDETAILS OD ON OD.ITEMID =I.ID 
GROUP BY 
I.ITEMCODE,I.ITEMNAME,I.BRAND,I.UNITPRICE,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3
 
