 
CREATE VIEW VWMONTHLYSALES
AS
SELECT
C.CITY SEHIR,DATEPART(MONTH,O.DATE_) AYNUMARASI,DATENAME(MONTH,O.DATE_)AYADI,
SUM(O.TOTALPRICE) TOPLAMTUTAR
FROM ORDERS O
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID

GROUP BY 
   C.CITY,DATEPART(MONTH,O.DATE_),DATENAME(MONTH,O.DATE_)
/*ORDER BY C.CITY ASC
*/
 