SELECT ID,REPLACE(NAMESURNAME,' '+SURNAME,'') NAME_,
SURNAME, NAMESURNAME FROM
(
SELECT ID,NAMESURNAME,
(SELECT top 1 value from string_split(NAMESURNAME,' ',1)  ORDER BY ordinal desc) SURNAME
FROM LAB08
) T

UPDATE LAB08 SET SURNAME=(SELECT top 1 value from string_split(NAMESURNAME,' ',1)  ORDER BY ordinal desc)
UPDATE LAB08 SET NAME_=REPLACE(NAMESURNAME,' '+SURNAME,'')